---
- name: Configure NTP on network devices using NetBox inventory config_context
  connection: network_cli
  hosts: device_roles_switch
  gather_facts: no
  become: true

  vars:
    ansible_user: admin
    ansible_password: admin
    ansible_become: yes
    ansible_become_password: admin

  tasks:
    - name: Extract NTP servers from NetBox inventory config_context
      set_fact:
        ntp_servers: "{{ hostvars[inventory_hostname].config_context[0].ntp_servers | default([]) }}"

    - name: Render NTP configuration using Jinja2 template
      template:
        src: templates/ntp_config.j2
        dest: /tmp/ntp_config_{{ inventory_hostname }}.yml

    - name: Apply NTP configuration to Arista EOS devices
      when: ansible_network_os == 'arista.eos.eos'
      arista.eos.eos_ntp_global:
        config: "{{ lookup('file', '/tmp/ntp_config_{{ inventory_hostname }}.yml') | from_yaml }}"
        state: replaced

    - name: Apply NTP configuration to Cisco IOS devcies
      when: ansible_network_os == 'cisco.ios.ios'
      arista.eos.eos_ntp_global:
        config: "{{ lookup('file', '/tmp/ntp_config_{{ inventory_hostname }}.yml') | from_yaml }}"
        state: replaced

    - name: Remove temporary NTP configuration files
      file:
        path: "/tmp/ntp_config_{{ inventory_hostname }}.yml"
        state: absent
