---
- name: Show running configuration on Arista EOS device
  connection: network_cli
  hosts: ceos1,ceos2,ceos3
  gather_facts: no
  become: true

  tasks:
    - name: Retrieve running configuration
      arista.eos.eos_command:
        commands: ["show running-config"]
      register: running_config

    - name: Display running configuration
      debug:
        var: running_config.stdout_lines
