---
- name: Listen for NTP Config Context updates from NetBox on a webhook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
  - name: NTP Configuration Updated
    condition:
     all:
        - event.payload.event == "updated"
        - event.payload.model == "configcontext"

    action:
      run_job_template:
        organization: "Default"
        name: "Configure NTP Servers"