---
- name: Listen for NTP Config Context updates from NetBox on a webhook when a branch is merged
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
  - name: NTP Configuration Updated
    # condition: event.payload.event == "job_ended"

    condition: >-
        event.payload.event == "job_ended" and
        event.payload.model == "branch" and
        "Applying change Extras | config context ntp_servers" in event.payload.data.log

    action:
      run_job_template:
        organization: "Default"
        name: "Configure NTP Servers"