---
- name: Listen for NTP Config Context updates from NetBox on a webhook when a branch is merged
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
  - name: NTP Configuration Updated
    condition:
      all:
        - event.payload.event == "job_ended"
        - event.payload.model == "branch"

    action:
      run_job_template:
        organization: "Default"
        name: "Configure NTP Servers"